ToDoListTrial/ToDoListTrial/ViewModels/ToDoListViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using ToDoListTrial.Models;

namespace ToDoListTrial.ViewModels
{
    public class ToDoListViewModel
    {
        public int ToDoListId { get; set; }
        public string ToDoListTitle { get; set; }

        public IEnumerable<ToDoList> ToDoLists { get; set; }
        public IEnumerable<ToDoItem> ToDoItems { get; set; }

        public string Message { get; set; }
    }
}

ToDoListTrial/ToDoListTrial/Controllers/ToDoItemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToDoListTrial.Context;
using ToDoListTrial.Models;
using ToDoListTrial.ViewModels;

namespace ToDoListTrial.Controllers
{
    public class ToDoItemController : Controller
    {
        private ToDoContext db = new ToDoContext();

        // GET: ToDoItem
        public ActionResult Index(int? toDoListId)
        {
            var model = new ToDoListViewModel();
            if (toDoListId != null)
            {
                ToDoList toDoList = db.ToDoLists.Find(toDoListId);
                if (toDoList == null)
                {
                    return HttpNotFound();
                }
                model.ToDoListId = toDoList.Id;
                model.ToDoListTitle = toDoList.Title;
                model.ToDoItems = GetTodoItems(toDoList.Id);
            }
            else
            {
                model.Message = "Yapılacaklar listesi seçmelisiniz.";
            }

            return View(model);
        }

        public IEnumerable<ToDoItem> GetTodoItems(int toDoListId)
        {
            var listItems = db.ToDoItems.ToList().Where(r => r.ToDoListId == toDoListId);

            return listItems;
        }

        // GET: ToDoItem/Create
        public ActionResult Create(int toDoListId)
        {
            var toDoItem = new ToDoItem()
            {
                ToDoListId = toDoListId,
                DueDate = DateTime.Now
            };
            return View(toDoItem);
        }

        // POST: ToDoItem/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include = "Id,ToDoListId,Content,DueDate")] ToDoItem toDoItem)
        {
            if (ModelState.IsValid)
            {
                toDoItem.CreateDate = DateTime.Now;
                toDoItem.IsActive = true;
                db.ToDoItems.Add(toDoItem);
                db.SaveChanges();
                return RedirectToAction("Index", new { toDoItem.ToDoListId });
            }

            return View(toDoItem);
        }

        // GET: ToDoItem/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDoItem toDoItem = db.ToDoItems.Find(id);
            if (toDoItem == null)
            {
                return HttpNotFound();
            }
            return View(toDoItem);
        }

        // POST: ToDoItem/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id,ToDoListId,Content,DueDate,CreateDate,IsActive")] ToDoItem toDoItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(toDoItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { toDoItem.ToDoListId });
            }
            return View(toDoItem);
        }

        // POST: ToDoItem/Delete/5
        [HttpPost]
        public JsonResult DeleteConfirmed(string id)
        {
            var _id = int.Parse(id);
            ToDoItem toDoItem = db.ToDoItems.Find(_id);
            db.ToDoItems.Remove(toDoItem);
            db.SaveChanges();
            return Json(new { redirectToUrl = Url.Action("Index","ToDoList", new { toDoItem.ToDoListId }) });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToDoListTrial/ToDoListTrial/Controllers/ToDoListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToDoListTrial.Context;
using ToDoListTrial.Models;
using ToDoListTrial.ViewModels;

namespace ToDoListTrial.Controllers
{
    public class ToDoListController : Controller
    {
        private ToDoContext db = new ToDoContext();

        // GET: ToDoList
        public ActionResult Index()
        {

            var model = new ToDoListViewModel();
            var toDoLists = db.ToDoLists.ToList();

            foreach (var toDoList in toDoLists)
            {
                toDoList.ToDoItems = GetTodoItems(toDoList.Id);
            }
            model.ToDoLists = toDoLists.OrderByDescending(r => r.CreateDate);

            return View(model);
        }

        public IEnumerable<ToDoItem> GetTodoItems(int toDoListId)
        {
            var listItems = db.ToDoItems.ToList().Where(r => r.ToDoListId == toDoListId);

            return listItems;
        }

        [HttpPost]
        public JsonResult GetExpiredItems()
        {
            var toDoLists = db.ToDoLists.ToList();

            foreach (var toDoList in toDoLists)
            {
                toDoList.ToDoItems = GetTodoItems(toDoList.Id).Where(r => r.DueDate <= DateTime.Now);
            }

            return Json(toDoLists, JsonRequestBehavior.AllowGet);
        }

        // GET: ToDoList/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDoList toDoList = db.ToDoLists.Find(id);
            if (toDoList == null)
            {
                return HttpNotFound();
            }
            return View(toDoList);
        }

        // GET: ToDoList/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ToDoList/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include = "Id,Title,Description")] ToDoList toDoList)
        {
            if (ModelState.IsValid)
            {
                toDoList.CreateDate = DateTime.Now;
                toDoList.IsActive = true;
                db.ToDoLists.Add(toDoList);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(toDoList);
        }

        // GET: ToDoList/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDoList toDoList = db.ToDoLists.Find(id);
            if (toDoList == null)
            {
                return HttpNotFound();
            }
            return View(toDoList);
        }

        // POST: ToDoList/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id,Title,Description,CreateDate,IsActive")] ToDoList toDoList)
        {
            if (ModelState.IsValid)
            {
                db.Entry(toDoList).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(toDoList);
        }

        // POST: ToDoList/Delete/5
        [HttpPost]
        public JsonResult DeleteConfirmed(string id)
        {
            var _id = int.Parse(id);
            ToDoList toDoList = db.ToDoLists.Find(_id);
            db.ToDoLists.Remove(toDoList);
            db.SaveChanges();
            return Json(new { redirectToUrl = Url.Action("Index") });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToDoListTrial/ToDoListTrial/Views/ToDoList/Create.cshtml
@model ToDoListTrial.Models.ToDoList

@{
    ViewBag.Title = "Yeni Yapılacaklar Listesi";
    Layout = "~/Views/Layout.cshtml";
}


<div class="container">
    @using (Html.BeginForm())
    {

        <div class="form-horizontal">
            <h4>Yeni Yapılacaklar Listesi</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="control-label col-md-2" for="Title">Başlık</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2" for="Description">Açıklama</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Ekle" class="btn btn-success" />
                    @Html.ActionLink("Geri Dön", "Index", null, new { @class = "btn btn-info" })
                </div>
            </div>
        </div>
    }
</div>

ToDoListTrial/ToDoListTrial/Views/ToDoList/Edit.cshtml
@model ToDoListTrial.Models.ToDoList

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Layout.cshtml";
}


<div class="container">
    @using (Html.BeginForm())
    {

        <div class="form-horizontal">
            <h4>@Model.Title</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.CreateDate)
            @Html.HiddenFor(model => model.IsActive)

            <div class="form-group">
                <label class="control-label col-md-2" for="Title">Başlık</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2" for="Description">Açıklama</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Kaydet" class="btn btn-success" />
                    @Html.ActionLink("Geri Dön", "Index", null, new { @class = "btn btn-info" })
                </div>
            </div>
        </div>
    }
</div>

ToDoListTrial/ToDoListTrial/Views/ToDoList/Index.cshtml
@model ToDoListTrial.ViewModels.ToDoListViewModel

@{
    ViewBag.Title = "Yapılacaklar";
    Layout = "~/Views/Layout.cshtml";
}

<div align="center">
    <p>
        @Html.ActionLink("Yeni Liste", "Create", null, new { @class = "btn btn-primary" })
    </p>
</div>

<div class="container">
    <div class="card-deck text-center">
        <div class="card-columns">
            @foreach (var item in Model.ToDoLists)
            {
                <div class="card border-primary">

                    <div class="card-body">
                        <h5 class="card-title">@Html.DisplayFor(modelItem => item.Title)</h5>
                        <p class="card-text">@Html.DisplayFor(modelItem => item.Description)</p>
                        <p class="card-text">@Html.DisplayFor(modelItem => item.CreateDate) tarihinde oluşturuldu.</p>
                    </div>

                    <ul class="list-group list-group-flush">
                        @foreach (var toDoItem in item.ToDoItems)
                        {
                            <li class="list-group-item" @(toDoItem.DueDate <= DateTime.Now ? "style=color:red; title=Expired!" : "")>@Html.DisplayFor(modelItem => toDoItem.Content)</li>
                        }
                    </ul>
                    <div class="card-body">
                        <a class="card-link text-white btn btn-success active text-center" href="@Url.Action("Index", "ToDoItem", new { toDoListId = item.Id })"> Detay </a> |
                        @Html.ActionLink("Düzenle", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" }) |
                        <button name="delete-list" value="@item.Id" class="btn btn-danger delete"> Sil </button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>